services:
    simplechannelchecker:
        container_name: simplechannelchecker
        image: gordlaben/simplechannelchecker:latest
        ports:
            - 1337:80
        environment:
            - SCC_PLAYLIST_PORT=1337 # change this only if you know what you are doing
            - WEB_HOSTNAME=127.0.0.1 # change this
        command: [ "python", "/app/main.py" ]
        volumes:
            - ./scc:/app/playlist
        restart: always

    dozzle:
        container_name: dozzle
        image: amir20/dozzle:latest
        #environment: # Visit to see how to add users.yml file to /dozzle/data folder https://dozzle.dev/guide/authentication#file-based-user-management
            #- DOZZLE_AUTH_PROVIDER=simple
            #- DOZZLE_AUTH_TTL=48h
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./dozzle/data:/data
        ports:
            - 3333:8080
        restart: unless-stopped
